[package]
name = "taffy-canvas-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
base64.workspace = true
indexmap.workspace = true
once_cell.workspace = true
quick-xml.workspace = true
rayon.workspace = true
regex.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
skia-safe.workspace = true
smallvec.workspace = true
taffy.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-metal = "0.3.2"
skia-safe = { workspace = true, features = ["gpu", "metal"] }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "render"
harness = false
