[package]
name = "taffy-canvas-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
indexmap.workspace = true
once_cell.workspace = true
quick-xml.workspace = true
rayon.workspace = true
regex.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
skia-safe.workspace = true
smallvec.workspace = true
taffy.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-metal = "0.3.2"
skia-safe = { workspace = true, features = ["gpu", "metal"] }

[target.'cfg(target_os = "linux")'.dependencies]
glutin = { version = "0.32.3", default-features = false, features = ["egl", "glx", "x11"] }
raw-window-handle = "0.6.2"
skia-safe = { workspace = true, features = ["gpu", "gl", "egl", "x11"] }

[target.'cfg(target_os = "windows")'.dependencies]
glutin = { version = "0.32.3", default-features = false, features = ["egl", "wgl"] }
raw-window-handle = "0.6.2"
skia-safe = { workspace = true, features = ["gpu", "gl"] }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "render"
harness = false
