[package]
name = "taffy-canvas-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true, features = ["serde-json"] }
napi-derive.workspace = true
serde.workspace = true
serde_json.workspace = true
taffy-canvas-core = { path = "../taffy-canvas-core" }
tokio.workspace = true

[build-dependencies]
napi-build = "2.3.1"
